version: "3.9"
services:
  pandora-github-runner:
    image: pandora-github-runner
    build: .
    env_file: .env
    deploy:
      replicas: 4
    restart: unless-stopped
    volumes:
      - type: tmpfs
        target: /home/docker,exec,mode=1777
        tmpfs:
          size: 2G
      - ./cache:/home/docker/.cache:rw
